import { Inter } from 'next/font/google'
// import { MetaMaskProvider } from '@metamask/sdk-react';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <MetaMaskProvider debug={false} sdkOptions={{
          checkInstallationImmediately: false,
          dappMetadata: {
            name: "Demo React App",
            url: window.location.host,
          }
        }}> */}
          {children}
        {/* </MetaMaskProvider> */}
      </body>
    </html>
  )
}
